simon-weber/python-libfaketime

setup.py

Stops `import test` import these tests wherever `python-libfaketime` is installed :)

Don't ship 'test' directory in package

---

README.rst
libfaketime/__init__.py
setup.py

When running `nosetests` or `python manage.py test` there are often left-over processes that are never reaped. As I use `watch` to run the tests every tenth of a second, that results in many, many processes :smile: 
I've traced this back to the re-exec that is performed. I would like to avoid that re-exec cleanly, but currently I have to have read the `libfaketime` source code to find out which envvars it wants. And keep the vars in sync ofcourse.
So, let's add a console script that prints out the needed envvars, like `ssh-agent` does on start. Then you can call `libfaketime` and it will output:
```bash
export LD_PRELOAD="/home/.../vendor/libfaketime/src/libfaketime.so.1"
export FAKETIME_DID_REEXEC=true
```
This can then be used at startup:
```bash
eval $(libfaketime)
nosetests
```

Add console command that prints needed envvars

---

libfaketime/__init__.py
test/test_faketime.py

Freezegun provides support for the `tick` method so I added it in here as well.
I didn't have much luck with the tests, two tests were already failing and when I added the tick test, the tests using the `_assert_time_not_faked` broke.
Thanks!

Add support for .tick()

---

README.rst

Everyone loves badges. I also added installation instructions since from the github page it's not obvious the PyPI name is just `libfaketime`. Plus I made some small amendments to syntax highlighting.

README - add badges and installation instructions

---

README.rst
libfaketime/__init__.py
test/test_faketime.py

My company uses libfaketime in our large test suite. We have found that deadlocks occur when generating uuid1s from the stdlib while within a fake_time context.
I have been able to reproduce these problems consistently from in our tests and the shell. We are only able to call uuid1() 11 times for a fake time period. In the test below, I'm showing that the same time is used between two context mangers and the deadlock occurs after the 11th call.
```
In [22]: time = datetime.now()
In [23]: with fake_time(time):
for i in range(10):
print uuid.uuid1()
....:
142d8626-0caa-11e6-b453-080027cebb63
142d8627-0caa-11e6-b453-080027cebb63
142d8628-0caa-11e6-b453-080027cebb63
142d8629-0caa-11e6-b453-080027cebb63
142d862a-0caa-11e6-b453-080027cebb63
142d862b-0caa-11e6-b453-080027cebb63 …
```

Deadlocks from using system level uuid1 generator

---

libfaketime/__init__.py
requirements.txt
setup.py

`contextdecorator` is a backport package for Python 2, as `ContextDecorator` was added to `contextlib` on Python 3.2+.

Use standard library ContextDecorator on Python 3

---

libfaketime/__init__.py

contextlib2 is another backport of Python 3's contextlib.  Some
distributions like Fedora ship this instead of contextdecorator so check
for both.

Try contextlib2 as alternative to contextdecorator on Python 2

---

test/test_faketime.py

I have a good processor, and this assertion fails half the time. By sleeping a microsecond, we are sure that it cannot fail.
It is not usually advised to call `time.sleep` in tests, but this is a very peculiar context, and it is only about a microsecond.

Ensures a microsecond has passed

---

libfaketime/__init__.py
test/test_faketime.py

This PR achieves the same goal than #27 and #1, but with a different approach, by playing with the TZ environment variable. It also fixes the issue with `datetime.utcnow` #35.
I got to this fix empirically, but I am not sure how I ended with the negative offset in the timezone. `os.environ['TZ'] = "UTC{0:+}".format(-self.tz_offset)`.

Timezone awareness, and utcnow fixes

---

README.rst
libfaketime/__init__.py
test/test_faketime.py

This PR simply adds a "freeze_time" alias, so compatibility with freezegun is just one import away. I think it can also help freezegun users to quickly test python-libfaketime.

Added a freeze_time alias

---

README.rst
requirements.txt
test/test_freezegun.py
tox.ini

Freezegun [mocks](https://github.com/spulec/freezegun/blob/master/freezegun/api.py#L17) `time.time`, `time.localtime`, `time.strftime`, `datetime.datetime.now`, `datetime.datetime.utcnow`, `datetime.date` and `datetime.datetime`. This (pytest) test checks that both libraries produce the same results under the same conditions, with and without timezone offsets.
For the moment, `time.localtime` and `time.strftime` produce different results. I expect to look at this later :)
This PR comes after #33 since it uses pytest parametrization \o/, so Travis should fail until #33 is merged.

Added a test to compare against freezegun mocked functions

---

CHANGELOG.rst
README.rst
conftest.py

This PR slightly improves the usage example, introduces tz_offset and pytest-libfaketime.
conftest.py is now pytest-xdist compatible
And I have edited the Changelog, maybe after this PR a pypi release would be appropriate?

Updated README

---

libfaketime/__init__.py
setup.py
test/test_faketime.py

It seems class decorator are not well handled here: a test class decorated with `fake_time` will be missed by pytest test discovery, resulting in tests being silently not executed !
You can test this by trying to run the tests provided in this PR with the current version of the lib vs with the patched one (you get 24 vs 26 tests passed...).
This PR solve the trouble by using the same class/function decorator system than in use in freezegun.

Add class decorator supporting pytest test discovery

---

CHANGELOG.rst
libfaketime/__init__.py
test/test_faketime.py

Hi. I had a special case:
- I need to decorate a whole class test, and I cannot decorate its methods or use a context manager because I need the class `setUp` method to be mocked.
- I need a way to call `fake_time.tick` in the method tests.
With this PR you can do `self._faked_time` and you can access the `fake_time` object in the test methods. I was not sure about implementing the same feature for methods.
What do you think?

Decorated objects can access fake_time with self._faked_time

---

README.rst

Updated pytest-libfaketime url in README

---

libfaketime/__init__.py

This fixes the problem where you have spaces in the path,
because LD_PRELOAD doesn't deal with it.
Should also fix issue #3

Make Linux use LD_LIBRARY_PATH and LD_PRELOAD

---

libfaketime/__init__.py
test/test_tz.py

My understanding of timezone code in Python is fairly limited, so please treat this as a proposal or a discussion point – it certainly needs review from someone with more understanding of the timezone ecosystem than myself.
That said, I believe what has happened here is that `python-libfaketime` is depending on `pytz` specific functionality – the `zone` attribute. From my exploration of the `pytz` and `dateutil` codebases, it _looks_ like the `tzname` method returns the same data. My understanding of the difference between `pytz` and `dateutil` is that with the former, `tzinfo` objects know about their owning `datetime`, whereas in the latter they don't (I could be wrong on this!).
This PR uses these assumptions to change `fake_time` to call `tzname(datetime_spec)` instead of using …

Fix compatibility with non-pytz tzinfo objects

---

README.md

I just asked for the transfer of pytest-libfaketime under the pytest-dev umbrella.

update pytest-libfaketime repository url

---

README.md
libfaketime/__init__.py
test/test_faketime.py

This PR depends on #75.
Il also fixes #70.
It adds a new parameter `timestamp_file` to `fake_time`. When passed, the date is written in this file, and the `FAKETIME_TIMESTAMP_FILE` environment variable is used instead of `FAKETIME`.
It also allows to not pass `datetime_spec` to `fake_time` when `timestamp_file` is passed, so the time value is simply read from the file.

timestamp files support

---

README.md

There was a missing triple backquote in the README file.
Also, @simon-weber, would you consider publishing a new release with the latest changes :pray: ?

fix README code closing tag
